module.exports = [
  "GUITAR","VOLCANO","ASTRONAUT","PIRATE","DRAGON","UMBRELLA","ROBOT","OCTOPUS","CASTLE","ROCKET",
  "PENGUIN","WIZARD","SKATEBOARD","LIGHTHOUSE","DINOSAUR","BACKPACK","SNOWMAN","TORNADO","MERMAID","TELESCOPE",
  "PANCAKE","HELICOPTER","CACTUS","VAMPIRE","IGLOO","KANGAROO","TRAMPOLINE","SUBMARINE","SCARECROW","WAFFLE",
  "GHOST","NINJA","VOLLEYBALL","PYRAMID","JELLYFISH","ACCORDION","CAMPFIRE","UNICORN","TYPEWRITER","AVALANCHE",
  "PARACHUTE","BEEHIVE","CATAPULT","FIREWORKS","GONDOLA","HAMMOCK","ICEBERG","JUKEBOX","KAYAK","LANTERN",
  "MUSHROOM","NARWHAL","OASIS","POPCORN","QUICKSAND","RAINBOW","SANDCASTLE","TREEHOUSE","URCHIN","VOLLEYVAN",
  "WINDMILL","XYLOPHONE","YOYO","ZEPPELIN","ANCHOR","BONFIRE","CANOE","DOMINO","ESCALATOR","FLAMINGO",
  "GARGOYLE","HOURGLASS","ICICLE","JIGSAW","KETTLE","LABYRINTH","MOSAIC","NUTCRACKER","ORIGAMI","PINWHEEL",
  "QUILL","RAFT","SNORKEL","TUMBLEWEED","UKULELE","VORTEX","WHIRLPOOL","YETI","ZIPLINE","ACORN",
  "BUBBLE","CHIMNEY","DRAWBRIDGE","EASEL","FOSSIL","GLACIER","HAMMER","INKWELL","JESTER","KNIGHT"
];
